---
title: "Lista de Exercícios 7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercício 1 - 10 pontos

<br>

## Matriz de custos:
```{r}
cij <- c(0, 36.9, 55, 13.6, 36.9, 0, 26.5, 33.8, 55, 26.5, 0, 45.8, 13.6, 33.8, 45.8, 0)
mult <- sqrt(length(cij))
print(matrix(cij, nrow=mult, ncol=mult))
```

<br>

## Modelo com restrição de sub-rota de Dantzig:

<br>

### Formulação:

<br>

Variáveis de decisão:

$$
x_{ij} =
\begin{cases}
 1, & \text{se o arco(i,j) faze parte do trajeto} \\
 0, & \text{caso contrario}
 \end{cases}       
$$

<br>

Função objetivo:

$$
\text{min z} = \sum \limits_{i=1}^4 \sum \limits_{j=1}^4 c_{ij} x_{ij}
$$

<br>

Sujeito a:

$$
x_{12} + x_{13} + x_{14} \geq 1
$$
$$
x_{21} + x_{23} + x_{24} \geq 1
$$
$$
x_{13} + x_{14} + x_{23} + x_{24} \geq 1
$$
$$
x_{31} + x_{32} + x_{34} \geq 1
$$
$$
x_{12} + x_{14} + x_{32} + x_{34} \geq 1
$$
$$
x_{21} + x_{24} + x_{31} + x_{34} \geq 1
$$

$$
x_{14} + x_{24} + x_{34} \geq 1
$$

$$
x_{41} + x_{42} + x_{43} \geq 1
$$

$$
x_{12} + x_{13} + x_{42} + x_{43} \geq 1
$$

$$
x_{21} + x_{23} + x_{41} + x_{43} \geq 1
$$

$$
x_{13} + x_{23} + x_{43} \geq 1
$$

$$
x_{31} + x_{32} + x_{41} + x_{42} \geq 1
$$

$$
x_{12} + x_{32} + x_{42} \geq 1
$$

$$
x_{21} + x_{31} + x_{41} \geq 1
$$

<br>

### Resolução:

<br>

Criação da matriz de restrições de sub-rota de Dantzig:
```{r}
# Todas as combinações:
comb <- as.data.frame(tidyr::crossing(var4=0:1, var3=0:1, var2=0:1, var1=0:1))
comb <- comb[,order(ncol(comb):1)]

# Eliminação das linhas compostas por apenas 0 ou 1:
comb$sum <- with(comb, var1 + var2 + var3 + var4)
comb <- comb[comb$sum > 0 & comb$sum < 4,]
comb$sum <- NULL
row.names(comb) <- 1:nrow(comb)

comb
```

```{r}
# Matriz de restrições:
for(i in 1:nrow(comb)) {
  dij <- matrix(data=0, nrow=mult, ncol=mult)
  for(j in 1:ncol(comb)) {
    vij <- comb[i, j]
    if(vij == 1) {
      for(k in 1:ncol(comb)) {
        vik <- comb[i, k]
        if(vik == 0) {
          dij[j, k] <- 1
        }
      }
    }
  }
  if(i == 1) {
    mat_restr <- as.integer(t(dij))
  } else {
    mat_restr <- rbind(mat_restr, as.integer(t(dij)))
  }
}

mat_restr <- as.matrix(mat_restr)
row.names(mat_restr) <- 1:nrow(mat_restr)
mat_restr

# Direção e RHS:
direcao <- rep(">=", nrow(mat_restr))
rhs <- rep(1, nrow(mat_restr))
```

<br>

Solução:
```{r}
s <- lpSolve::lp(direction = "min",
        objective.in = cij,
        const.mat = mat_restr,
        const.dir = direcao,
        const.rhs = rhs)
s

xij <- s$solution
xij <- matrix(xij, nrow=mult, ncol=mult)
xij
```

